//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SimplesE.BasicIntegrationConsole.SimplesEService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SimplesEService.ICoreService")]
    public interface ICoreService {
        
        [System.ServiceModel.OperationContractAttribute(ProtectionLevel=System.Net.Security.ProtectionLevel.Sign, Action="http://tempuri.org/ICoreService/InsertUser", ReplyAction="http://tempuri.org/ICoreService/InsertUserResponse")]
        SimplesE.Model.Service.ServiceResult<SimplesE.Model.Core.User> InsertUser(SimplesE.Model.Core.User user);
        
        [System.ServiceModel.OperationContractAttribute(ProtectionLevel=System.Net.Security.ProtectionLevel.Sign, Action="http://tempuri.org/ICoreService/InsertUser", ReplyAction="http://tempuri.org/ICoreService/InsertUserResponse")]
        System.Threading.Tasks.Task<SimplesE.Model.Service.ServiceResult<SimplesE.Model.Core.User>> InsertUserAsync(SimplesE.Model.Core.User user);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICoreServiceChannel : SimplesE.BasicIntegrationConsole.SimplesEService.ICoreService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CoreServiceClient : System.ServiceModel.ClientBase<SimplesE.BasicIntegrationConsole.SimplesEService.ICoreService>, SimplesE.BasicIntegrationConsole.SimplesEService.ICoreService {
        
        public CoreServiceClient() {
        }
        
        public CoreServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CoreServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CoreServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CoreServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public SimplesE.Model.Service.ServiceResult<SimplesE.Model.Core.User> InsertUser(SimplesE.Model.Core.User user) {
            return base.Channel.InsertUser(user);
        }
        
        public System.Threading.Tasks.Task<SimplesE.Model.Service.ServiceResult<SimplesE.Model.Core.User>> InsertUserAsync(SimplesE.Model.Core.User user) {
            return base.Channel.InsertUserAsync(user);
        }
    }
}
